name: Spec
on:
  push:
    paths:
      - '**/*.rb'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run RSpec
      run: bundle exec rspec
